// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFWebAPI.Data;

#nullable disable

namespace SFWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SFWebAPI.Models.Player", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PlayerId"));

                    b.Property<short?>("Experience")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("GameMoney")
                        .HasColumnType("SMALLINT");

                    b.Property<bool?>("IsLevel1Clear")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsLevel2Clear")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsLevel3Clear")
                        .HasColumnType("tinyint(1)");

                    b.Property<short?>("Level")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("RealMoney")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("RequiredExp")
                        .HasColumnType("SMALLINT");

                    b.Property<short?>("TotalGameCount")
                        .HasColumnType("SMALLINT");

                    b.Property<long?>("UserId")
                        .HasColumnType("BIGINT");

                    b.Property<short?>("WinGameCount")
                        .HasColumnType("SMALLINT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SFWebAPI.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("UserId");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
